# This question is asked by Google.
# You are given two strings, s and t which only consist of lowercase letters.
# t is generated by shuffling the letters in s as well as potentially adding an additional random character.
# Return the letter that was randomly added to t if it exists, otherwise, return ’  ‘.
# Note: You may assume that at most one additional character can be added to t.

import re
import unittest

class Solution:
    def check(self, s: str, t: str) -> str:
        text_match = re.search(rf"[^{s}]", t)

        if text_match:
            return text_match.group(0)

        return ''


class Solution2:
    def check(self, s: str, t: str) -> str:
        additional_chars: str = ''

        for char in t:
            if char not in s:
                additional_chars += char

        return additional_chars


class Solution3:
    def check(self, s: str, t: str) -> str:
        additional_chars: str = ''
        left: int = 0
        right: int = len(t) - 1

        while left < right:
            if t[left] not in s:
                additional_chars += t[left]

            if t[right] not in s:
                additional_chars += t[right]

            left += 1
            right -= 1

        return additional_chars


class TestSolution(unittest.TestCase):
    def setUp(self):
        self.solution = Solution()
        self.solution2 = Solution2()
        self.solution3 = Solution3()

    def test_1(self):
        self.assertEqual(self.solution.check('foobar', 'barfoot'), 't')
        self.assertEqual(self.solution2.check('foobar', 'barfoot'), 't')
        self.assertEqual(self.solution3.check('foobar', 'barfoot'), 't')

    def test_2(self):
        self.assertEqual(self.solution.check('ide', 'idea'), 'a')
        self.assertEqual(self.solution2.check('ide', 'idea'), 'a')
        self.assertEqual(self.solution3.check('ide', 'idea'), 'a')

    def test_3(self):
        self.assertEqual(self.solution.check('coding', 'ingcod'), '')
        self.assertEqual(self.solution2.check('coding', 'ingcod'), '')
        self.assertEqual(self.solution3.check('coding', 'ingcod'), '')

if __name__ == "__main__":
    unittest.main()
